### ISSUE TITLE
USB_BACKEND_LIBUSB (e.g., on FreeBSD) fails to build

### ISSUE THREAD

**Issue by jbeich** [whoozle/android-file-transfer-linux#220]
Regressed by 07ea91498976. See [error log](https://github.com/whoozle/android-file-transfer-linux/files/3193480/android-file-transfer-qt5-3.8.log).

```c++
mtp/usb/BulkPipe.cpp:36:13: error: no member named 'ClearHalt' in 'mtp::usb::Device'
                { device->ClearHalt(in); }
                  ~~~~~~  ^
mtp/usb/BulkPipe.cpp:41:13: error: no member named 'ClearHalt' in 'mtp::usb::Device'
                { device->ClearHalt(out); }
                  ~~~~~~  ^
2 errors generated.
```

**Comment by whoozle** [comment]
thanks a lot for reporting it!
